[package]
name = "abelscreensaver"
version = "0.1.0"
edition = "2021"

[dependencies]
auto_enums = "0.8.5"
bisection = "0.1.0"
eframe = "0.27.2"
image = "0.24.9"
mime_guess = "2.0.4"
rand = "0.8.5"
structopt = "0.3.26"
walkdir = "2.5.0"
egui-video = { version = "0.6.0", default-features = false, path="../egui-video/" }
